#+TITLE: Quiz on Docker Compose

*Question 1:*

Which is the minimum recommended version for a docker-compose.yml file?

- [ ] 1
- [X] 2
- [ ] 3.1

*Queston 2:*

Which of the following does "docker-compose up" automatically create, even if
not manually specified in the compose file?

- [X] Network
- [ ] Backup
- [ ] Pizza
- [ ] Registry

*Question 3:*

What is the 'build context' in a compose file supposed to do?

- [ ] The build has to occur before the run command
- [ ] The image in reference has to exist in a Docker Hub repo before being run
- [ ] docker-compose should build an image from the context of the most recent
  image built in a previous compose file
- [X] It is meant to specify where the Dockerfile of the image is supposed to
  build from

*Question 4:*

The "ports:" key in a compose file does the same thing as the EXPOSE stanza in a
Dockerfile.

- [ ] True
- [X] False

*Question 5:*

Usernames for a database, when placed in a compose file of a specific service,
would best fit placed under which of the following keys?

- [ ] image:
- [X] environment:
- [ ] identify:
- [ ] volumes:

*Question 6:*

Where does compose derive a DNS name from?

- [X] service names
- [ ] image names
- [ ] volume names
- [ ] reddit usernames
